language: node_js
node_js:
    - "0.10"
services:
    - mongodb
before_script:
    - sleep 15
    - ./tests/setup.sh
env:
    global:
        - "VALID_USER=test"
        - "VALID_PASS=test123"
        - "INVALID_USER=test"
        - "INVALID_PASS=test"
        - "DATABASE=test"
        - "DB_USER=sessionHandler"
        - "DB_PASS=supersecretpassword"
        - "TTL=300"
