language: node_js
node_js:
    - "0.10"
services:
    - mongodb
before_script:
    - sleep 15
    - ./tests/setup.js
    - ./tests/setup2.js
env:
    global:
        - "VALID_CRUSER=test"
        - "VALID_CRPASS=test123"
        - "LOCAL_USER=test@test.com"
        - "LOCAL_PASS=test123"
        - "INVALID_USER=test"
        - "INVALID_PASS=test"
        - "DATABASE=test"
        - "DB_USER=sessionHandler"
        - "DB_PASS=supersecretpassword"
        - "TTL=300"
